update

diff --git a/.github/workflows/sr_cfg.yml b/.github/workflows/sr_cfg.yml
--- a/.github/workflows/sr_cfg.yml
+++ b/.github/workflows/sr_cfg.yml
@@ -54,7 +54,7 @@ jobs:
       # DIRECT RULES
       # RAW_RULESET_DIRECT_URL:             https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaMax/ChinaMax.list
       RAW_LIST_DIRECT_IP_URL:             https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaIPs/ChinaIPs_IP.txt
-      RAW_RULESET_DIRECT_IP_URL:          https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaIPs/ChinaIPs.list
+      # RAW_RULESET_DIRECT_URL:             https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaIPs/ChinaIPs.list
       # RAW_RULESET_DIRECT_DOMAIN_URL:      https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/direct.txt
       RAW_RULESET_DIRECT_DOMAIN_URL:      https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/refs/heads/master/accelerated-domains.china.conf
 
@@ -140,7 +140,7 @@ jobs:
           # Download Block Rules
           touch $GITHUB_WORKSPACE/tmp/block_drop_ruleset.txt
           curl -sSL ${{ env.RAW_RULESET_IPV4_DROP_URL }} | sed -nE 's/\{"cidr":"([^"]+)".*/\1/p' | python3 $GITHUB_WORKSPACE/script/merge_ip_addr.py | sed -E -e 's/^/IP-CIDR,/' -e 's/$/,no-resolve/' >> $GITHUB_WORKSPACE/tmp/block_drop_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_IPV4_DROP_URL }} Failed!" && exit 1)
-          curl -sSL ${{ env.RAW_RULESET_IPV6_DROP_URL }} | sed -nE 's/\{"cidr":"([^"]+)".*/\1/p' | python3 $GITHUB_WORKSPACE/script/merge_ip_addr.py | sed -E -e 's/^/IP-CIDR6,/' -e 's/$/,no-resolve/' >> $GITHUB_WORKSPACE/tmp/block_drop_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_IPV6_DROP_URL }} Failed!" && exit 1)
+          curl -sSL ${{ env.RAW_RULESET_IPV6_DROP_URL }} | sed -nE 's/\{"cidr":"([^"]+)".*/\1/p' | python3 $GITHUB_WORKSPACE/script/merge_ip_addr.py | sed -E -e 's/^/IP-CIDR,/' -e 's/$/,no-resolve/' >> $GITHUB_WORKSPACE/tmp/block_drop_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_IPV6_DROP_URL }} Failed!" && exit 1)
           touch $GITHUB_WORKSPACE/tmp/block_ruleset.txt
           curl -sSL ${{ env.RAW_RULESET_BLOCK_URL }} >> $GITHUB_WORKSPACE/tmp/block_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_BLOCK_URL }} Failed!" && exit 1)
           curl -sSL ${{ env.RAW_RULESET_BLOCKHTTPDNS_URL }} >> $GITHUB_WORKSPACE/tmp/block_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_BLOCKHTTPDNS_URL }} Failed!" && exit 1)
@@ -183,7 +183,7 @@ jobs:
                                                             $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/apple.txt \
                                                             > /dev/null
           sed -i -e 's/^/  - /' -e '1i\payload:' $GITHUB_WORKSPACE/release/mhm/rule-provider/yaml/apple.yaml
-          sed -e 's/DOMAIN-REGEX/URL-REGEX/' -e 's/IP-CIDR6/IP-CIDR/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/apple.txt > $GITHUB_WORKSPACE/release/sr/rule-set/apple.txt
+          sed -e 's/DOMAIN-REGEX/URL-REGEX/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/apple.txt > $GITHUB_WORKSPACE/release/sr/rule-set/apple.txt
 
       - name: Process High Priority Rules
         run: |
@@ -195,23 +195,23 @@ jobs:
 
           python3 $GITHUB_WORKSPACE/script/customize_ruleset.py -m add_and_remove -i $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_direct.txt -p $GITHUB_WORKSPACE/customization/high_priority_direct.txt
           sed -e 's/^/  - /' -e '1i\payload:' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_direct.txt > $GITHUB_WORKSPACE/release/mhm/rule-provider/yaml/high_priority_direct.yaml
-          sed -e 's/DOMAIN-REGEX/URL-REGEX/' -e 's/IP-CIDR6/IP-CIDR/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_direct.txt > $GITHUB_WORKSPACE/release/sr/rule-set/high_priority_direct.txt
+          sed -e 's/DOMAIN-REGEX/URL-REGEX/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_direct.txt > $GITHUB_WORKSPACE/release/sr/rule-set/high_priority_direct.txt
 
           python3 $GITHUB_WORKSPACE/script/customize_ruleset.py -m add_and_remove -i $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_proxy.txt -p $GITHUB_WORKSPACE/customization/high_priority_proxy.txt
           sed -e 's/^/  - /' -e '1i\payload:' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_proxy.txt > $GITHUB_WORKSPACE/release/mhm/rule-provider/yaml/high_priority_proxy.yaml
-          sed -e 's/DOMAIN-REGEX/URL-REGEX/' -e 's/IP-CIDR6/IP-CIDR/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_proxy.txt > $GITHUB_WORKSPACE/release/sr/rule-set/high_priority_proxy.txt
+          sed -e 's/DOMAIN-REGEX/URL-REGEX/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_proxy.txt > $GITHUB_WORKSPACE/release/sr/rule-set/high_priority_proxy.txt
 
           python3 $GITHUB_WORKSPACE/script/customize_ruleset.py -m add_and_remove -i $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_warp1.txt -p $GITHUB_WORKSPACE/customization/high_priority_warp1.txt
           sed -e 's/^/  - /' -e '1i\payload:' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_warp1.txt > $GITHUB_WORKSPACE/release/mhm/rule-provider/yaml/high_priority_warp1.yaml
-          sed -e 's/DOMAIN-REGEX/URL-REGEX/' -e 's/IP-CIDR6/IP-CIDR/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_warp1.txt > $GITHUB_WORKSPACE/release/sr/rule-set/high_priority_warp1.txt
+          sed -e 's/DOMAIN-REGEX/URL-REGEX/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_warp1.txt > $GITHUB_WORKSPACE/release/sr/rule-set/high_priority_warp1.txt
 
           python3 $GITHUB_WORKSPACE/script/customize_ruleset.py -m add_and_remove -i $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_warp2.txt -p $GITHUB_WORKSPACE/customization/high_priority_warp2.txt
           sed -e 's/^/  - /' -e '1i\payload:' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_warp2.txt > $GITHUB_WORKSPACE/release/mhm/rule-provider/yaml/high_priority_warp2.yaml
-          sed -e 's/DOMAIN-REGEX/URL-REGEX/' -e 's/IP-CIDR6/IP-CIDR/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_warp2.txt > $GITHUB_WORKSPACE/release/sr/rule-set/high_priority_warp2.txt
+          sed -e 's/DOMAIN-REGEX/URL-REGEX/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_warp2.txt > $GITHUB_WORKSPACE/release/sr/rule-set/high_priority_warp2.txt
 
           python3 $GITHUB_WORKSPACE/script/customize_ruleset.py -m add_and_remove -i $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_warp3.txt -p $GITHUB_WORKSPACE/customization/high_priority_warp3.txt
           sed -e 's/^/  - /' -e '1i\payload:' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_warp3.txt > $GITHUB_WORKSPACE/release/mhm/rule-provider/yaml/high_priority_warp3.yaml
-          sed -e 's/DOMAIN-REGEX/URL-REGEX/' -e 's/IP-CIDR6/IP-CIDR/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_warp3.txt > $GITHUB_WORKSPACE/release/sr/rule-set/high_priority_warp3.txt
+          sed -e 's/DOMAIN-REGEX/URL-REGEX/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/high_priority_warp3.txt > $GITHUB_WORKSPACE/release/sr/rule-set/high_priority_warp3.txt
 
       - name: Process Warp Rules
         run: |
@@ -222,7 +222,7 @@ jobs:
                                                            $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/warp.txt \
                                                            > /dev/null
           sed -i -e 's/^/  - /' -e '1i\payload:' $GITHUB_WORKSPACE/release/mhm/rule-provider/yaml/warp.yaml
-          sed -e 's/DOMAIN-REGEX/URL-REGEX/' -e 's/IP-CIDR6/IP-CIDR/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/warp.txt > $GITHUB_WORKSPACE/release/sr/rule-set/warp.txt
+          sed -e 's/DOMAIN-REGEX/URL-REGEX/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/warp.txt > $GITHUB_WORKSPACE/release/sr/rule-set/warp.txt
 
       - name: Process LAN Rules
         run: |
@@ -231,25 +231,31 @@ jobs:
                                                           $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/lan.txt \
                                                           > /dev/null
           sed -i -e 's/^/  - /' -e '1i\payload:' $GITHUB_WORKSPACE/release/mhm/rule-provider/yaml/lan.yaml
-          sed -e 's/DOMAIN-REGEX/URL-REGEX/' -e 's/IP-CIDR6/IP-CIDR/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/lan.txt > $GITHUB_WORKSPACE/release/sr/rule-set/lan.txt
+          sed -e 's/DOMAIN-REGEX/URL-REGEX/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/lan.txt > $GITHUB_WORKSPACE/release/sr/rule-set/lan.txt
 
       - name: Process Direct Rules
         run: |
+          # customize direct domains
+          python3 $GITHUB_WORKSPACE/script/customize_ruleset.py -m remove_from_adding_list -i $GITHUB_WORKSPACE/tmp/direct_ruleset.txt -p $GITHUB_WORKSPACE/customization/apple.txt
+          python3 $GITHUB_WORKSPACE/script/customize_ruleset.py -m add_and_remove -i $GITHUB_WORKSPACE/tmp/direct_ruleset.txt -p $GITHUB_WORKSPACE/customization/direct_domains.txt
+          python3 $GITHUB_WORKSPACE/script/sort_ruleset.py $GITHUB_WORKSPACE/tmp/direct_ruleset.txt
+
+          cat $GITHUB_WORKSPACE/tmp/direct_ruleset.txt | sed 's/DOMAIN-SUFFIX,\|DOMAIN,//g' > $GITHUB_WORKSPACE/release/text/direct_domains.txt
           # add lan rules to direct ruleset
           cat $GITHUB_WORKSPACE/tmp/lan_ruleset.txt >> $GITHUB_WORKSPACE/tmp/direct_ruleset.txt
           # process direct ip list
           python3 $GITHUB_WORKSPACE/script/merge_ip_addr.py $GITHUB_WORKSPACE/tmp/direct_ip_list.txt | sed -E -e 's/^/IP-CIDR,/' -e 's/$/,no-resolve/' >> $GITHUB_WORKSPACE/tmp/direct_ruleset.txt
-          # process direct ruleset
+          # remove redundancy
           python3 $GITHUB_WORKSPACE/script/customize_ruleset.py -m remove_redundancy -i $GITHUB_WORKSPACE/tmp/direct_ruleset.txt
-          # remove apple domains from direct rules
-          python3 $GITHUB_WORKSPACE/script/customize_ruleset.py -m remove_from_adding_list -i $GITHUB_WORKSPACE/tmp/direct_ruleset.txt -p $GITHUB_WORKSPACE/customization/apple.txt
-          python3 $GITHUB_WORKSPACE/script/customize_ruleset.py -m add_and_remove -i $GITHUB_WORKSPACE/tmp/direct_ruleset.txt -p $GITHUB_WORKSPACE/customization/direct.txt
+          # reorder
+          python3 $GITHUB_WORKSPACE/script/sort_ruleset.py $GITHUB_WORKSPACE/tmp/direct_ruleset.txt
+          # write to other directories
           python3 $GITHUB_WORKSPACE/script/sort_ruleset.py $GITHUB_WORKSPACE/tmp/direct_ruleset.txt
           cat $GITHUB_WORKSPACE/tmp/direct_ruleset.txt | tee $GITHUB_WORKSPACE/release/mhm/rule-provider/yaml/direct.yaml \
                                                              $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/direct.txt \
                                                              > /dev/null
           sed -i -e 's/^/  - /' -e '1i\payload:' $GITHUB_WORKSPACE/release/mhm/rule-provider/yaml/direct.yaml
-          sed -e 's/DOMAIN-REGEX/URL-REGEX/' -e 's/IP-CIDR6/IP-CIDR/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/direct.txt > $GITHUB_WORKSPACE/release/sr/rule-set/direct.txt
+          sed -e 's/DOMAIN-REGEX/URL-REGEX/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/direct.txt > $GITHUB_WORKSPACE/release/sr/rule-set/direct.txt
 
       - name: Process Proxy Rules
         run: |
@@ -262,7 +268,7 @@ jobs:
                                                             $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/proxy.txt \
                                                             > /dev/null
           sed -i -e 's/^/  - /' -e '1i\payload:' $GITHUB_WORKSPACE/release/mhm/rule-provider/yaml/proxy.yaml
-          sed -e 's/DOMAIN-REGEX/URL-REGEX/' -e 's/IP-CIDR6/IP-CIDR/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/proxy.txt > $GITHUB_WORKSPACE/release/sr/rule-set/proxy.txt
+          sed -e 's/DOMAIN-REGEX/URL-REGEX/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/proxy.txt > $GITHUB_WORKSPACE/release/sr/rule-set/proxy.txt
 
       - name: Process Block Rules
         run: |
@@ -289,10 +295,10 @@ jobs:
                                                                  > /dev/null
 
           sed -i -e 's/^/  - /' -e '1i\payload:' $GITHUB_WORKSPACE/release/mhm/rule-provider/yaml/block.yaml
-          sed -e 's/DOMAIN-REGEX/URL-REGEX/' -e 's/IP-CIDR6/IP-CIDR/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/block.txt > $GITHUB_WORKSPACE/release/sr/rule-set/block.txt
+          sed -e 's/DOMAIN-REGEX/URL-REGEX/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/block.txt > $GITHUB_WORKSPACE/release/sr/rule-set/block.txt
 
           sed -i -e 's/^/  - /' -e '1i\payload:' $GITHUB_WORKSPACE/release/mhm/rule-provider/yaml/block_drop.yaml
-          sed -e 's/DOMAIN-REGEX/URL-REGEX/' -e 's/IP-CIDR6/IP-CIDR/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/block_drop.txt > $GITHUB_WORKSPACE/release/sr/rule-set/block_drop.txt
+          sed -e 's/DOMAIN-REGEX/URL-REGEX/' $GITHUB_WORKSPACE/release/mhm/rule-provider/txt/block_drop.txt > $GITHUB_WORKSPACE/release/sr/rule-set/block_drop.txt
 
       - name: Process SR Domain-DNS Rules
         run: |
